docker-compose-yaml: docker-compose.yml

project: lab-tests-online

tasks:
  post-rollout:
    - run:
        name: IF no Drupal installed and we are not LIVE branch, sync from DEV branch
        command: |
          if tables=$(drush sqlq 'show tables;') && [ -z "$tables" ] && [[ "$LAGOON_GIT_BRANCH" != "live" ]]; then
              # no drupal installed, sync DB from dev branch
              drush -y sql-sync @lagoon.dev @self
          fi
        service: cli
        shell: bash
    - run:
        name: IF on a new PR environment (not on Dev/Test/Live), sync files from LIVE branch
        command: |
          if tables=$(drush sqlq 'show tables;') && [ -z "$tables" ]; then
              drush -y rsync @lagoon.live:%files @self:%files
          fi
        service: cli
        shell: bash
    - run:
        name: drush cr
        command: drush cr
        service: cli
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli

environments:
  live:
    routes:
      - nginx:
        - 'www.labtestsonline.org.uk':
              tls-acme: 'true'
              insecure: Redirect
        - 'labtestsonline.org.uk':
              tls-acme: 'true'
              insecure: Redirect
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
