<?php

/**
 * @file
 * Contains top_content_views.module.
 */

/**
 * Implements hook_theme().
 */
function top_content_views_theme($existing, $type, $theme, $path) {
  return [
    'top_content' => [
      'variables' => [
        'TopTests' => NULL,
        'TopConditions' => NULL,
        'TopScreenings' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function top_content_views_theme_suggestions_container_alter(array &$suggestions, array $variables) {
  if (isset($variables['element']['#type'], $variables['element']['#name']) && $variables['element']['#type'] == 'view' && $variables['element']['#name'] == 'tests_conditions_screenings') {
    $suggestions[] = 'container__' . $variables['element']['#name'];
  }
}
