title: 'Bize Yorumlarınızı Gönderin'
elements: |
  instructions:
    '#text': "<p>Please provide your feedback on the article you are reading, or about Lab Tests Online in general. This will help us improve the site. Thank you.</p>\n"
  find_what_you_are_looking_for:
    '#title': 'Aradığınızı buldunuz mu?'
  find_information:
    '#title': 'Kolayca buldunuz mu?'
