<?php

/**
 * @file
 * Contains aacc_screening_test_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function aacc_screening_test_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the aacc_screening_test_entity module.
    case 'help.page.aacc_screening_test_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module creates a custom entity for Screening Tests') . '</p>';
      return $output;

    default:
  }
}
