<?php

/**
 * @file
 * Contains external_link.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function external_link_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the external_link module.
    case 'help.page.external_link':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module creates and registers the External Link entity type.') . '</p>';
      return $output;

    default:
  }
}
